### ISSUE TITLE
Looks like setReleaseBranchPatterns doesn't work

### ISSUE THREAD

**Issue by to4kin** [sergii-kuku/gradle-git-plugin#1]
I'm trying to extend the release branch pattern:

gitData.setReleaseBranchPatterns(["(.*)release/(.*)", "(.*)hotfix/(.*)"])

The output:

parsing HEAD
parse HEAD returned release/20.4.2.0
verifying rev release/20.4.2.0
gitData returned with branchType = DEV_BRANCH, short rev = 20.4.2.0, full rev = origin/release/20.4.2.0, commit hash = c87d7b9, tags = N/A, number of commits = 190
parsing HEAD
parse HEAD returned release/20.4.2.0
verifying rev release/20.4.2.0
gitData returned with branchType = DEV_BRANCH, short rev = 20.4.2.0, full rev = origin/release/20.4.2.0, commit hash = c87d7b9, tags = N/A, number of commits = 190

How I can change the branch type to RELEASE?

**Comment by to4kin** [comment]
Ok, I found the problem. From the plugin code:

return additionalReleaseBranchPatterns.stream().anyMatch(shortBranchName::matches)

Is it possible to compare additionalReleaseBranchPatterns not only with shortBranchName, but also with (or only) with full branch name?

**Comment by sergii-kuku** [comment]
It is possible. It was actually the case before my changes from this
weekend. Version 1.1.0 still has such logic.
If you open a PR, I think I can merge and release it this evening (CET).

**Comment by to4kin** [comment]
I tried to create a PR, but receive 403 error. Actually, it's my first PR, so it could be my problem :) You can check changes here https://github.com/to4kin/gradle-git-plugin/commit/eae26fb56a5613eb620dac4f9cb6ccd938a37ba3

**Comment by to4kin** [comment]
I don't know what changed, but now it works

**Comment by sergii-kuku** [comment]
Glad it does. Seems legit. Thank you for the contribution. I will update docs and release a new version today.
In fact, I believe that your change does make more sense than checking against the short name.

**Comment by sergii-kuku** [comment]
Your PR is merged. Closing the issue.

**Comment by sergii-kuku** [comment]
Please check the new version: 1.2.2

**Comment by to4kin** [comment]
Super! Now it works as expected! Thank you
