### ISSUE TITLE
Numeric identifier MUST NOT contain leading zeroes

### ISSUE THREAD

**Issue by to4kin** [sergii-kuku/gradle-git-plugin#3]
Looks like we faced with another issue:

```
> Configure project :
parsing HEAD
parse HEAD returned v20.0.0-dev.85.TVPP.8541.move.all.configs.from.DB.to.YAML.0406662
verifying rev v20.0.0-dev.85.TVPP.8541.move.all.configs.from.DB.to.YAML.0406662
gitData returned with branchType = DEV_BRANCH, short rev = v20.0.0-dev.85.TVPP.8541.move.all.configs.from.DB.to.YAML.0406662, full rev = v20.0.0-dev.85.TVPP.8541.move.all.configs.from.DB.to.YAML.0406662, commit hash = 04066626, tags = N/A, number of commits = 1045
git rev-parse --verify origin/v20.0.0-dev.85.TVPP.8541.move.all.configs.from.DB.to.YAML.0406662 failed
fatal: Needed a single revision
git rev-parse --verify refs/tags/v20.0.0-dev.85.TVPP.8541.move.all.configs.from.DB.to.YAML.0406662 failed
fatal: Needed a single revision
parsing HEAD
parse HEAD returned v20.0.0-dev.85.TVPP.8541.move.all.configs.from.DB.to.YAML.0406662
verifying rev v20.0.0-dev.85.TVPP.8541.move.all.configs.from.DB.to.YAML.0406662
gitData returned with branchType = DEV_BRANCH, short rev = v20.0.0-dev.85.TVPP.8541.move.all.configs.from.DB.to.YAML.0406662, full rev = v20.0.0-dev.85.TVPP.8541.move.all.configs.from.DB.to.YAML.0406662, commit hash = 04066626, tags = N/A, number of commits = 1045
git rev-parse --verify origin/v20.0.0-dev.85.TVPP.8541.move.all.configs.from.DB.to.YAML.0406662 failed
fatal: Needed a single revision
git rev-parse --verify refs/tags/v20.0.0-dev.85.TVPP.8541.move.all.configs.from.DB.to.YAML.0406662 failed
fatal: Needed a single revision
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred evaluating script.
> Numeric identifier MUST NOT contain leading zeroes
```

From my point of view the problem in the hash commit, because it's started with leading '0'. I'm not sure that we never had hash with leading '0', but the previous commit works fine

**Comment by to4kin** [comment]
One additional point. The failed build is in tag, if we try to build the app in branch - everything is fine

**Comment by sergii-kuku** [comment]
It looks like semver regex parsing error and hence not directly linked to the plugin.
What regex are you using for the release branch detection?

In general, using git hashes in release versions, specifically compliant with semver, might lead to random errors like you had.

**Comment by to4kin** [comment]
We use the following regex:

gitData.setReleaseBranchPatterns([
        "(.*)hotfix(-|/)\\d+\\.\\d+\\.\\d+(\\.\\d+)\$",
        "(.*)release(-|/)\\d+\\.\\d+\\.\\d+(\\.\\d+)\$"
])

And the problem only appears in the Tag, in the branch everything is ok. So mb we can somehow disable the plugin for builds in the tag?

**Comment by to4kin** [comment]
Hi again, the problem is not in your plugin. The problem in the semantic version plugin inside gradle. I am sorry for disturbing
